### ISSUE TITLE
deprecated 'lsp-common

### ISSUE THREAD

**Issue by mpanarin** [emacs-lsp-legacy/lsp-python#33]
As `lsp-common` no longer exists, it produces an error
`File mode specification error: (file-missing Cannot open load file No such file or directory lsp-common)`

n.b. spacemacs on emacs 26.1

**Comment by yyoncho** [comment]
you have to use https://github.com/syl20bnr/spacemacs/pull/11626

**Comment by wilkystyle** [comment]
@yyoncho How about for those of us not using Spacemacs? Experiencing the same thing here.

**Comment by dpkatz** [comment]
Same problem.  I'm running on vanilla Emacs 26.1.

**Comment by yyoncho** [comment]
@wilkystyle @dpkatz this package is deprecated, please take a look at the lsp-mode.el README.- https://github.com/emacs-lsp/lsp-mode

In short:

1. lsp-python is no longer needed
2. Any other configuration except (add-hook 'python-mode-hook 'lsp) is not needed. lsp-mode will auto-configure company-mode/flycheck/lsp-ui and so on. 

here it is all that you need to make lsp-mode.el work as before:

```
(use-package lsp-mode
  :config
  (require 'lsp-clients)
  (add-hook 'python-mode-hook 'lsp))
(use-package company-lsp)
(use-package lsp-ui)
```

**Comment by wilkystyle** [comment]
@yyoncho: Got it. Confirmed that removing the `lsp-python` package and simply adding `(add-hook 'python-mode-hook 'lsp)` to my `lsp-mode` config worked.

**Comment by DougBeney** [comment]
If you use lsp with multiple languages, perhaps `prog-mode-hook` would be more efficient in your configuration.

```
(use-package lsp-mode
  :config
  (require 'lsp-clients)
  (add-hook 'prog-mode-hook 'lsp))
```

I'm still new to `use-package` but perhaps another way to keep your lsp configuration neat is to put the additional lsp-related use-package statements within the lsp-mode use-package, like so:

```
(use-package lsp-mode
  :config
  ;;; Enable lsp in all programming modes
  (require 'lsp-clients)
  (add-hook 'prog-mode-hook 'lsp)

  ;;; Additional lsp-related packages
  (use-package company-lsp)
  (use-package lsp-ui))
```

**Comment by yyoncho** [comment]
@DougBeney at this point this is config will cause some problems when you open a file and you do not have the corresponding language server(it will print errors) but we are working on fixing this.
